set nocompatible
colo evening
set relativenumber
inoremap jk <esc>
nnoremap <space> :
set shiftwidth=4
set ts=4
set sts=4
set autoindent
set nowrap
"set expandtab
set modeline
syntax on

augroup yaml
  autocmd!

  autocmd BufNewFile *.yaml setl ft=yaml sw=2 ts=2 sts=2 et
augroup END
