#!/bin/sh
## This file is executed during VNC server startup.

test x"$SHELL" = x"" && SHELL=/bin/bash
test x"$1"     = x"" && set -- default

# keyboard -----
#if test -r /etc/default/keyboard &&
#   test -x /usr/bin/setxkbmap; then
#  . /etc/default/keyboard
#  /usr/bin/setxkbmap \
#    -model   "${XKBMODEL}" \
#    -layout  "${XKBLAYOUT}" \
#    -variant "${XKBVARIANT}" \
#    "${XKBOPTIONS}"
#fi
# ---

#unset SESSION_MANAGER

export XDG_SESSION_TYPE='x11'
export XDG_RUNTIME_DIR="$HOME/.cache"
export SHELL='/bin/bash'

#export GTK_MODULES=gail:atk-bridge
export QT_ACCESSIBILITY=1
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_QPA_PLATFORMTHEME=qt5ct

export XDG_DATA_DIRS=/usr/local/share/:/usr/share/:/usr/share
export TERMINAL="qterminal"

# input method -----
# fcitx5 -----
export INPUT_METHOD=fcitx5
export QT_IM_MODULE=fcitx5
export GTK_IM_MODULE=fcitx
export CLUTTER_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
/usr/bin/fcitx5 &
# ---

# ibus -----
#export GTK_IM_MODULE=ibus
#export CLUTTER_IM_MODULE=ibus
#export QT_IM_MODULE=ibus
#export XMODIFIERS=@im=ibus
#/usr/bin/ibus-daemon -d -x -r &
# ---
# ---

vncconfig -iconic &
#"$SHELL" -l <<EOF
#exec /etc/X11/Xsession "$@"
#EOF

# Window manager/Desktop environment -----
#dbus-launch --exit-with-session startxfce4
dbus-launch --exit-with-session i3
# ---

# vim: ai:et:ts=2:sw=2:sts=2:tw=80:ft=sh:fmr=\ -----,---:fdm=marker
